# Generated by Django 5.0.9 on 2024-10-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vl_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Vialogos id"
                    ),
                ),
                (
                    "mb_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Metabooks id",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Short Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "person_or_company",
                    models.CharField(
                        choices=[("F", "Person"), ("J", "Company")],
                        default="J",
                        max_length=1,
                        verbose_name="Person or Company",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, max_length=18, null=True, verbose_name="CNPJ"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "state_registration",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="State Registration",
                    ),
                ),
                (
                    "municipal_registration",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Municipal Registration",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Contact Person",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "emailnfe",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email NFe"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=120, verbose_name="Street")),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Number"
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Complement"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="State"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="District"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Zip Code"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Address",
                "verbose_name_plural": "Supplier Addresses",
                "ordering": ["supplier", "street"],
            },
        ),
        migrations.CreateModel(
            name="SupplierCNPJ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, max_length=18, null=True, verbose_name="CNPJ"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier CNPJ",
                "verbose_name_plural": "Supplier CNPJs",
                "ordering": ["supplier", "cnpj"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Phone",
                "verbose_name_plural": "Supplier Phones",
                "ordering": ["supplier", "phone_number"],
            },
        ),
    ]
