# Generated by Django 5.0.2 on 2024-02-27 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='cpf',
        ),
        migrations.CreateModel(
            name='SupplierCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier CNPJ',
                'verbose_name_plural': 'Supplier CNPJs',
                'ordering': ['supplier', 'cnpj'],
            },
        ),
    ]
