# Generated by Django 5.0.2 on 2024-02-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplieraddress_created_supplieraddress_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieraddress',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome curto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vl_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código do Vialogos'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Logradouro'),
        ),
    ]
