# Generated by Django 5.0.2 on 2024-02-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_remove_supplieraddress_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='supplieraddress',
            options={'ordering': ['supplier', 'street'], 'verbose_name': 'Endereço de Fornecedor', 'verbose_name_plural': 'Endereços de Fornecedores'},
        ),
    ]
