# Generated by Django 5.0.2 on 2024-02-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_remove_supplier_vl_id_supplier_internal_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='supplieraddress',
            options={'ordering': ['supplier', 'street'], 'verbose_name': 'Supplier Address', 'verbose_name_plural': 'Supplier Addresses'},
        ),
    ]
