# Generated by Django 5.0.2 on 2024-02-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_supplier_cpf_supplier_emailnfe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieraddress',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Number'),
        ),
    ]
