# Generated by Django 5.0.2 on 2024-03-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_supplieraddress_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='person_or_company',
            field=models.CharField(blank=True, choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, null=True, verbose_name='Person or Company'),
        ),
    ]
