# Generated by Django 5.0.2 on 2024-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_supplier_options_alter_supplieraddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieraddress',
            name='complement',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='short_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='street',
            field=models.CharField(max_length=120, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Zip Code'),
        ),
    ]
