# Generated by Django 5.0.2 on 2024-03-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_alter_supplier_person_or_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='internal_id',
        ),
        migrations.AddField(
            model_name='supplier',
            name='mb_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Metabooks id'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vl_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vialogos id'),
        ),
    ]
