# Generated by Django 5.0.3 on 2024-03-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_remove_supplier_internal_id_supplier_mb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='supplieraddress',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='suppliercnpj',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='supplierphone',
            name='modified',
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='suppliercnpj',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='supplierphone',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
