# Generated by Django 5.0.3 on 2024-03-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0011_remove_supplier_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieraddress",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Zip Code"
            ),
        ),
    ]
