# Generated by Django 5.0.3 on 2024-03-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0012_alter_supplieraddress_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="person_or_company",
            field=models.CharField(
                choices=[("F", "Person"), ("J", "Company")],
                default="J",
                max_length=1,
                verbose_name="Person or Company",
            ),
        ),
    ]
