# Generated by Django 5.0.2 on 2024-02-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Status do Grupo de Produtos',
                'verbose_name_plural': 'Status dos Grupos de Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('customer_limit_date', models.DateField(blank=True, null=True, verbose_name='Data limite para o cliente')),
                ('supplier_limit_date', models.DateField(blank=True, null=True, verbose_name='Data limite para o fornecedor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Produtos')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_groups.productgroupstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Grupo de Produtos',
                'verbose_name_plural': 'Grupos de Produtos',
                'ordering': ['name'],
            },
        ),
    ]
