# Generated by Django 5.0.3 on 2024-03-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0018_rename_is_cover_productimage_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('OR', 'Ordered'), ('SE', 'In Separation'), ('FI', 'Finished'), ('CA', 'Canceled'), ('AR', 'Archived')], default='PE', max_length=2, verbose_name='Status')),
                ('customer_limit_date', models.DateField(blank=True, null=True, verbose_name='Limit Date for the Customer')),
                ('supplier_limit_date', models.DateField(blank=True, null=True, verbose_name='Limit Date for the Supplier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Products Group',
                'verbose_name_plural': 'Products Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='product_groups.productgroup', verbose_name='Group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Group Item',
                'verbose_name_plural': 'Product Group Items',
                'ordering': ['group', 'product'],
            },
        ),
    ]
