# Generated by Django 5.0.2 on 2024-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('OR', 'Ordered'), ('SE', 'In Separation'), ('FI', 'Finished'), ('CA', 'Cancelled'), ('AR', 'Archived')], default='PE', max_length=2, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='ProductGroupStatus',
        ),
    ]
