# Generated by Django 5.0.3 on 2024-03-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='modified',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
