# Generated by Django 5.0.2 on 2024-02-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0002_alter_productgroup_status_delete_productgroupstatus'),
        ('products', '0004_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'verbose_name': 'Products Group', 'verbose_name_plural': 'Products Groups'},
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='customer_limit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Limit Date for the Customer'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_groups', to='products.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='supplier_limit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Limit Date for the Supplier'),
        ),
    ]
