# @name ping
GET https://{{ $dotenv MC_PREFIX }}.{{ $dotenv MC_URL }}/ping HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv MC_KEY}}

###

# @name get_campaigns
GET https://{{ $dotenv MC_PREFIX }}.{{ $dotenv MC_URL }}/campaigns HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv MC_KEY}}

###

@campaign_id = {{ get_campaigns.response.body.campaigns.0.id }}

# @name get_campaign_info
GET https://{{ $dotenv MC_PREFIX }}.{{ $dotenv MC_URL }}/campaigns/{{ campaign_id }} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv MC_KEY}}

###

# @name get_campaign_contents
GET https://{{ $dotenv MC_PREFIX }}.{{ $dotenv MC_URL }}/campaigns/{{ campaign_id }}/content HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv MC_KEY}}

###

# @name get_templates
GET https://{{ $dotenv MC_PREFIX }}.{{ $dotenv MC_URL }}/templates HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv MC_KEY}}

###

@template_id = {{ get_templates.response.body.templates.0.id }}

# @name get_template_info
GET https://{{ $dotenv MC_PREFIX }}.{{ $dotenv MC_URL }}/templates/{{ template_id }} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv MC_KEY}}

###

# @name get_template_content
GET https://{{ $dotenv MC_PREFIX }}.{{ $dotenv MC_URL }}/templates/{{ template_id }}/default-content HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv MC_KEY}}
