# Generated by Django 5.0.2 on 2024-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vldados', '0002_delete_agrfin_delete_alunos_delete_analcgr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espec',
            fields=[
                ('codigo', models.CharField(db_collation='Latin1_General_CI_AI', db_column='CODIGO', max_length=3, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='NOME', max_length=45, null=True)),
                ('estante', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='ESTANTE', max_length=50, null=True)),
                ('wpress', models.IntegerField(blank=True, db_column='WPRESS', null=True)),
                ('catavento', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='CATAVENTO', max_length=50, null=True)),
                ('li', models.IntegerField(blank=True, db_column='LI', null=True)),
            ],
            options={
                'db_table': 'ESPEC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('nbook', models.CharField(db_collation='Latin1_General_CI_AI', db_column='NBOOK', max_length=6, primary_key=True, serialize=False)),
                ('disp', models.IntegerField(blank=True, db_column='DISP', null=True)),
                ('reserva', models.IntegerField(blank=True, db_column='RESERVA', null=True)),
                ('qtped', models.IntegerField(blank=True, db_column='QTPED', null=True)),
                ('exame', models.IntegerField(blank=True, db_column='EXAME', null=True)),
                ('consig', models.IntegerField(blank=True, db_column='CONSIG', null=True)),
                ('dtatu', models.DateTimeField(blank=True, db_column='DTATU', null=True)),
                ('di', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='DI', max_length=1, null=True)),
                ('dp', models.IntegerField(blank=True, db_column='DP', null=True)),
                ('ev', models.IntegerField(blank=True, db_column='EV', null=True)),
                ('filial', models.CharField(db_collation='Latin1_General_CI_AI', db_column='FILIAL', max_length=3)),
                ('locest', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='LOCEST', max_length=40, null=True)),
                ('qtsep', models.IntegerField(blank=True, db_column='QTSEP', null=True)),
                ('atualizar', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Atualizar', max_length=1, null=True)),
                ('cod_ff', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='COD_FF', max_length=6, null=True)),
                ('disp_ff', models.IntegerField(blank=True, db_column='DISP_FF', null=True)),
                ('li', models.BooleanField(blank=True, db_column='LI', null=True)),
                ('cad_ok', models.BooleanField(blank=True, db_column='CAD_OK', null=True)),
                ('codprod_ff', models.IntegerField(blank=True, db_column='CODPROD_FF', null=True)),
            ],
            options={
                'db_table': 'ESTOQUE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('nbook', models.CharField(db_collation='Latin1_General_CI_AI', db_column='NBOOK', max_length=6, primary_key=True, serialize=False)),
                ('publisher', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='PUBLISHER', max_length=6, null=True)),
                ('supplier', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='SUPPLIER', max_length=6, null=True)),
                ('author', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='AUTHOR', max_length=20, null=True)),
                ('title', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='TITLE', max_length=75, null=True)),
                ('edition', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='EDITION', max_length=4, null=True)),
                ('volume', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='VOLUME', max_length=6, null=True)),
                ('binding', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='BINDING', max_length=1, null=True)),
                ('subj1', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='SUBJ1', max_length=3, null=True)),
                ('statcd', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='STATCD', max_length=1, null=True)),
                ('statdt', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='STATDT', max_length=8, null=True)),
                ('list', models.FloatField(blank=True, db_column='LIST', null=True)),
                ('tpprod', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='TPPROD', max_length=3, null=True)),
                ('di', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='DI', max_length=1, null=True)),
                ('qtpag', models.IntegerField(blank=True, db_column='QTPAG', null=True)),
                ('nsuppl', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='NSUPPL', max_length=10, null=True)),
                ('moeda', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='MOEDA', max_length=3, null=True)),
                ('dtcad', models.DateTimeField(blank=True, db_column='DTCAD', null=True)),
                ('dtatual', models.DateTimeField(blank=True, db_column='DTATUAL', null=True)),
                ('dtlcto', models.DateTimeField(blank=True, db_column='DTLCTO', null=True)),
                ('autor', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='AUTOR', max_length=100, null=True)),
                ('subj2', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='SUBJ2', max_length=3, null=True)),
                ('subj3', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='SUBJ3', max_length=3, null=True)),
                ('peso', models.FloatField(blank=True, db_column='PESO', null=True)),
                ('formato', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='FORMATO', max_length=10, null=True)),
                ('ano', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='ANO', max_length=4, null=True)),
                ('colecao', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='COLECAO', max_length=100, null=True)),
                ('isbn1', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='ISBN1', max_length=13, null=True)),
                ('sellpr', models.FloatField(blank=True, db_column='SELLPR', null=True)),
                ('disc', models.FloatField(blank=True, db_column='DISC', null=True)),
                ('flagpr', models.BooleanField(blank=True, db_column='FLAGPR', null=True)),
                ('prcusto', models.FloatField(blank=True, db_column='PRCUSTO', null=True)),
                ('marca', models.BooleanField(blank=True, db_column='MARCA', null=True)),
                ('cadlocal', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='CADLOCAL', max_length=1, null=True)),
                ('cst', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='CST', max_length=3, null=True)),
                ('desccli', models.FloatField(blank=True, db_column='DESCCLI', null=True)),
                ('unid', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='UNID', max_length=4, null=True)),
                ('ativo', models.BooleanField(blank=True, db_column='ATIVO', null=True)),
                ('estmin', models.IntegerField(blank=True, db_column='ESTMIN', null=True)),
                ('flagdados', models.BooleanField(blank=True, db_column='FLAGDADOS', null=True)),
                ('descricao', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='DESCRICAO', max_length=140, null=True)),
                ('mgatacado', models.FloatField(blank=True, db_column='MGATACADO', null=True)),
                ('mgvarejo', models.FloatField(blank=True, db_column='MGVAREJO', null=True)),
                ('conservacao', models.TextField(blank=True, db_collation='Latin1_General_CI_AI', db_column='CONSERVACAO', null=True)),
            ],
            options={
                'db_table': 'livros',
                'managed': False,
            },
        ),
    ]
