# Generated by Django 5.0.2 on 2024-03-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabookssync',
            name='bearer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
