# Generated by Django 5.0.2 on 2024-02-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Internal id')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug')),
                ('short_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Short Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('cnpj', models.CharField(blank=True, max_length=14, unique=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=11, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('contact_person', models.CharField(blank=True, max_length=120, null=True, verbose_name='Contact Person')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=120, null=True, verbose_name='Complement')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Zip Code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['customer', 'street'],
            },
        ),
    ]
