# Generated by Django 5.0.2 on 2024-02-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cnpj",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="CNPJ"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="CPF"
            ),
        ),
    ]
