# Generated by Django 5.0.2 on 2024-02-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['customer', 'street'], 'verbose_name': 'Endereço de Cliente', 'verbose_name_plural': 'Endereços de Clientes'},
        ),
    ]
