# Generated by Django 5.0.2 on 2024-02-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customeraddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['customer', 'street'], 'verbose_name': 'Customer Address', 'verbose_name_plural': 'Customer Addresses'},
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='complement',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='short_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(max_length=120, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Zip Code'),
        ),
    ]
