# Generated by Django 5.0.2 on 2024-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_cnpj_alter_customer_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='Slug'),
        ),
    ]
