# Generated by Django 5.0.2 on 2024-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='internal_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Internal id'),
        ),
    ]
