# Generated by Django 5.0.2 on 2024-02-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Contact Person'),
        ),
    ]
