# Generated by Django 5.0.2 on 2024-02-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sheet_label',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Sheet Label'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Name'),
        ),
    ]
