# Generated by Django 5.0.2 on 2024-02-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_sheet_label_alter_customer_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='emailnfe',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email NFe'),
        ),
        migrations.AddField(
            model_name='customer',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Municipal Registration'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person_or_company',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Person or Company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State Registration'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='short_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Number'),
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Phone',
                'verbose_name_plural': 'Customer Phones',
                'ordering': ['customer', 'phone'],
            },
        ),
    ]
