# Generated by Django 5.0.2 on 2024-02-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customer_phone_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerphone',
            options={'ordering': ['customer', 'phone_number'], 'verbose_name': 'Customer Phone', 'verbose_name_plural': 'Customer Phones'},
        ),
        migrations.RenameField(
            model_name='customerphone',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
