# Generated by Django 5.0.2 on 2024-02-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customerphone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['short_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
