# Generated by Django 5.0.2 on 2024-03-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customer_person_or_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='person_or_company',
            field=models.CharField(blank=True, choices=[('F', 'Person'), ('J', 'Company')], max_length=1, null=True, verbose_name='Person or Company'),
        ),
    ]
