# Generated by Django 5.0.3 on 2024-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_remove_customer_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="person_or_company",
            field=models.CharField(
                choices=[("F", "Person"), ("J", "Company")],
                default="J",
                max_length=1,
                verbose_name="Person or Company",
            ),
        ),
    ]
