# Generated by Django 5.0.3 on 2024-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0013_alter_customer_person_or_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="vl_created",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vialogos Created at"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="vl_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vialogos Updated at"
            ),
        ),
    ]
