# Generated by Django 5.0.3 on 2024-04-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_alter_customeraddress_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerphone",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="customers.customer",
            ),
        ),
    ]
