# Generated by Django 5.0.2 on 2024-02-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal ID'),
        ),
    ]
