# Generated by Django 5.0.3 on 2024-03-04 16:39

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), output_field=models.DecimalField(decimal_places=2, max_digits=10000), verbose_name='Subtotal'),
        ),
    ]
