# Generated by Django 5.0.3 on 2024-03-04 16:43

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemhistory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='orderitemhistory',
            name='subtotal',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), output_field=models.DecimalField(decimal_places=2, max_digits=10000), verbose_name='Subtotal'),
        ),
    ]
