# Generated by Django 5.0.2 on 2024-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitemhistory_price_orderitemhistory_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Canceled at'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='canceled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Canceled at'),
        ),
    ]
