# Generated by Django 5.0.2 on 2024-03-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_canceled_orderitem_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Delivered Quantity'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('FI', 'Finished'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
    ]
