# Generated by Django 5.0.9 on 2024-10-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vl_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Vialogos id"
                    ),
                ),
                (
                    "mb_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Metabooks id",
                    ),
                ),
                (
                    "supplier_internal_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Supplier Internal id",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="SKU"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10000,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "mb_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10000,
                        null=True,
                        verbose_name="Metabooks Price",
                    ),
                ),
                (
                    "vl_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10000,
                        null=True,
                        verbose_name="Vialogos Price",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Stock")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "mb_created",
                    models.DateField(
                        blank=True, null=True, verbose_name="Metabooks created at"
                    ),
                ),
                (
                    "mb_updated",
                    models.DateField(
                        blank=True, null=True, verbose_name="Metabooks updated at"
                    ),
                ),
                (
                    "vl_created",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vialogos created at"
                    ),
                ),
                (
                    "vl_updated",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vialogos updated at"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.productcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/images", verbose_name="Image"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Is Cover"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["product", "-created"],
            },
        ),
        migrations.CreateModel(
            name="ProductReleaseDateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_date", models.DateField(verbose_name="Release Date")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_dates",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Release Date History",
                "verbose_name_plural": "Product Release Date Histories",
                "ordering": ["product", "release_date"],
            },
        ),
    ]
