# Generated by Django 5.0.2 on 2024-02-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('OR', 'Ordered'), ('SE', 'In Separation'), ('FI', 'Finished'), ('CA', 'Cancelled'), ('AR', 'Archived')], default='PE', max_length=2, verbose_name='Status')),
                ('customer_limit_date', models.DateField(blank=True, null=True, verbose_name='Limit Date for the Customer')),
                ('supplier_limit_date', models.DateField(blank=True, null=True, verbose_name='Limit Date for the Supplier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Products Group',
                'verbose_name_plural': 'Products Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Internal id')),
                ('supplier_internal_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Supplier Internal id')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, max_length=13, null=True, verbose_name='SKU')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True, verbose_name='Price')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Supplier')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', to='products.productgroup', verbose_name='Group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Group Item',
                'verbose_name_plural': 'Product Group Items',
                'ordering': ['group', 'product'],
            },
        ),
        migrations.CreateModel(
            name='ProductReleaseDateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_dates', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Release Date History',
                'verbose_name_plural': 'Product Release Date Histories',
                'ordering': ['product', '-release_date'],
            },
        ),
    ]
