# Generated by Django 5.0.2 on 2024-02-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0004_remove_supplieraddress_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_id', models.IntegerField(blank=True, null=True, verbose_name='Código do Vialogos')),
                ('supplier_code', models.IntegerField(blank=True, null=True, verbose_name='Código do Fornecedor')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True, verbose_name='Preço')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de lançamento')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Estoque')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Fornecedor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='Categoria')),
            ],
        ),
    ]
