# Generated by Django 5.0.2 on 2024-02-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug_alter_product_supplier'),
        ('suppliers', '0005_alter_supplier_options_alter_supplieraddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Fornecedor'),
        ),
    ]
