# Generated by Django 5.0.2 on 2024-02-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreleasedatehistory',
            options={'ordering': ['product', '-created'], 'verbose_name': 'Product Release Date History', 'verbose_name_plural': 'Product Release Date Histories'},
        ),
    ]
