# Generated by Django 5.0.2 on 2024-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_local',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='internal_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Internal id'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_internal_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Supplier id'),
        ),
    ]
