# Generated by Django 5.0.2 on 2024-02-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_id_local_remove_product_id_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_internal_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Supplier Internal id'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('OR', 'Ordered'), ('SE', 'In Separation'), ('FI', 'Finished'), ('CA', 'Cancelled'), ('AR', 'Archived')], default='PE', max_length=2, verbose_name='Status')),
                ('customer_limit_date', models.DateField(blank=True, null=True, verbose_name='Limit Date for the Customer')),
                ('supplier_limit_date', models.DateField(blank=True, null=True, verbose_name='Limit Date for the Supplier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('products', models.ManyToManyField(blank=True, related_name='product_groups', to='products.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Products Group',
                'verbose_name_plural': 'Products Groups',
                'ordering': ['name'],
            },
        ),
    ]
