# Generated by Django 5.0.2 on 2024-03-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productreleasedatehistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroupitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='products.productgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='productgroupitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='products.product', verbose_name='Product'),
        ),
    ]
