# Generated by Django 5.0.2 on 2024-02-21 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_supplier_internal_id_productgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReleaseDateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_dates', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Release Date History',
                'verbose_name_plural': 'Product Release Date Histories',
                'ordering': ['product', '-release_date'],
            },
        ),
    ]
