# Generated by Django 5.0.2 on 2024-02-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreleasedatehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isbn',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='SKU'),
        ),
    ]
