# Generated by Django 5.0.2 on 2024-03-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('OR', 'Ordered'), ('SE', 'In Separation'), ('FI', 'Finished'), ('CA', 'Canceled'), ('AR', 'Archived')], default='PE', max_length=2, verbose_name='Status'),
        ),
    ]
