# Generated by Django 5.0.3 on 2024-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productgroup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Metabooks Category',
                'verbose_name_plural': 'Product Metabooks Categories',
                'ordering': ['name'],
            },
        ),
    ]
