# Generated by Django 5.0.3 on 2024-03-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productmbcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mb_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productmbcategory', verbose_name='Metabooks Category'),
        ),
    ]
