# Generated by Django 5.0.3 on 2024-03-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_mb_category_product_mb_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mb_categories',
        ),
        migrations.DeleteModel(
            name='ProductMBCategory',
        ),
    ]
