# Generated by Django 5.0.3 on 2024-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_mb_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mb_created',
            field=models.DateField(blank=True, null=True, verbose_name='Metabooks created at'),
        ),
        migrations.AddField(
            model_name='product',
            name='mb_modified',
            field=models.DateField(blank=True, null=True, verbose_name='Metabooks modified at'),
        ),
        migrations.AddField(
            model_name='product',
            name='vl_created',
            field=models.DateField(blank=True, null=True, verbose_name='Vialogos created at'),
        ),
        migrations.AddField(
            model_name='product',
            name='vl_modified',
            field=models.DateField(blank=True, null=True, verbose_name='Vialogos modified at'),
        ),
    ]
