# Generated by Django 5.0.3 on 2024-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_mb_created_product_mb_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mb_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True, verbose_name='Metabooks Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='vl_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True, verbose_name='Vialogos Price'),
        ),
    ]
