# Generated by Django 5.0.3 on 2024-03-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_cover',
            new_name='is_main',
        ),
    ]
