# Generated by Django 5.0.3 on 2024-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0020_remove_product_mb_modified_remove_product_modified_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="mb_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Metabooks id"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier_internal_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Supplier Internal id",
            ),
        ),
    ]
