# Generated by Django 5.0.3 on 2024-04-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_product_mb_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productreleasedatehistory",
            options={
                "ordering": ["product", "release_date"],
                "verbose_name": "Product Release Date History",
                "verbose_name_plural": "Product Release Date Histories",
            },
        ),
    ]
